import org.jetbrains.kotlin.gradle.ExperimentalWasmDsl
import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    alias(libs.plugins.kotlin.multiplatform)
    alias(libs.plugins.android.kotlin.multiplatform.library)
    alias(libs.plugins.kotlin.serialization)
    alias(libs.plugins.detekt)
}

detekt {
    buildUponDefaultConfig = true
    config.setFrom(files("$rootDir/config/detekt/detekt.yml"))
    baseline = file("detekt-baseline.xml")
    source.setFrom(files("src"))
}

kotlin {
    jvmToolchain(17)

    jvm()

    android {
        namespace = "com.cloudbasepredictor.engine"
        compileSdk = 36
        minSdk = 25
        compilerOptions {
            jvmTarget.set(JvmTarget.JVM_17)
        }
    }

    @OptIn(ExperimentalWasmDsl::class)
    wasmJs {
        // Without an explicit name, artifacts inherit the root project name
        // ("Cloudbase predictor-engine.wasm", with a space).
        outputModuleName.set("engine")
        nodejs()
    }

    sourceSets {
        commonTest.dependencies {
            implementation(libs.kotlin.test)
            implementation(libs.kotlinx.serialization.json)
        }
    }
}

// The golden fixture JSON must be readable from commonTest on every target
// (JVM and Wasm have no shared resource-loading API), so it is embedded as a
// generated Kotlin source. Chunked appends keep each string literal below the
// JVM class-file limit of 65535 UTF-8 bytes per constant.
val generateGoldenFixtureSource = tasks.register("generateGoldenFixtureSource") {
    description = "Embeds the golden fixture JSON as a generated commonTest source."
    val fixtureFile = layout.projectDirectory.file("src/commonTest/resources/brauneck_icon_seamless.json")
    val outputDir = layout.buildDirectory.dir("generated/goldenFixture")
    inputs.file(fixtureFile)
    outputs.dir(outputDir)
    doLast {
        val escapedChunks = fixtureFile.asFile.readText().chunked(20_000).map { chunk ->
            chunk
                .replace("\\", "\\\\")
                .replace("\"", "\\\"")
                .replace("$", "\\$")
                .replace("\n", "\\n")
        }
        val targetFile = outputDir.get()
            .file("com/cloudbasepredictor/domain/forecast/GoldenFixtureJson.kt").asFile
        targetFile.parentFile.mkdirs()
        targetFile.writeText(
            buildString {
                appendLine("// Generated by :engine:generateGoldenFixtureSource from")
                appendLine("// src/commonTest/resources/brauneck_icon_seamless.json. Do not edit.")
                appendLine("package com.cloudbasepredictor.domain.forecast")
                appendLine()
                appendLine("internal val goldenFixtureJson: String = buildString {")
                escapedChunks.forEach { appendLine("    append(\"$it\")") }
                appendLine("}")
            },
        )
    }
}

kotlin.sourceSets.commonTest {
    kotlin.srcDir(generateGoldenFixtureSource)
}
